const c=document.getElementById('game'),x=c.getContext('2d');x.imageSmoothingEnabled=false;
const W=c.width,H=c.height,keys={};let prevButtons=[];
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);
const walls=[{x:0,y:0,w:320,h:12},{x:0,y:168,w:320,h:12},{x:0,y:0,w:12,h:180},{x:308,y:0,w:12,h:180},{x:62,y:40,w:58,h:12},{x:200,y:38,w:55,h:12},{x:75,y:118,w:42,h:12},{x:205,y:122,w:65,h:12}];
const p={x:35,y:85,w:10,h:12,s:1.25,hp:5,dir:'down',cool:0,ifr:0};
const enemy={x:244,y:80,w:12,h:12,hp:3,alive:true,hit:0};const chest={x:270,y:142,w:13,h:10,open:false};let won=false,msg='Find the old chest.';
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function blocked(nx,ny){const q={x:nx,y:ny,w:p.w,h:p.h};return walls.some(w=>hit(q,w))}
function gamepad(){const g=navigator.getGamepads?.()[0];if(!g)return {dx:0,dy:0,a:false,i:false};let dx=Math.abs(g.axes[0]||0)>.22?g.axes[0]:0,dy=Math.abs(g.axes[1]||0)>.22?g.axes[1]:0;const b=g.buttons,pressed=n=>!!b[n]?.pressed;const a=pressed(0)&&!prevButtons[0],i=pressed(2)&&!prevButtons[2];prevButtons=b.map(v=>v.pressed);if(pressed(14))dx=-1;if(pressed(15))dx=1;if(pressed(12))dy=-1;if(pressed(13))dy=1;return{dx,dy,a,i}}
function attack(){if(p.cool>0)return;p.cool=18;let a={x:p.x-3,y:p.y-3,w:p.w+6,h:p.h+6};if(p.dir==='left')a.x-=9;if(p.dir==='right')a.x+=9;if(p.dir==='up')a.y-=9;if(p.dir==='down')a.y+=9;if(enemy.alive&&hit(a,enemy)){enemy.hp--;enemy.hit=8;if(enemy.hp<=0){enemy.alive=false;msg='The path is clear. Find the chest.'}}}
function interact(){const q={x:p.x-8,y:p.y-8,w:p.w+16,h:p.h+16};if(hit(q,chest)&&!chest.open){chest.open=true;won=true;msg='You found the GREEN RELIC! Prototype complete.'}}
function update(){const g=gamepad();let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+g.dx,dy=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+g.dy;if(dx||dy){const m=Math.hypot(dx,dy)||1;dx/=m;dy/=m;if(Math.abs(dx)>Math.abs(dy))p.dir=dx<0?'left':'right';else p.dir=dy<0?'up':'down';let nx=p.x+dx*p.s,ny=p.y;if(!blocked(nx,ny))p.x=nx;nx=p.x;ny=p.y+dy*p.s;if(!blocked(nx,ny))p.y=ny}if((keys.Space||g.a)&&p.cool<=0)attack();if((keys.KeyE||g.i)){interact();keys.KeyE=false}if(p.cool>0)p.cool--;if(p.ifr>0)p.ifr--;if(enemy.hit>0)enemy.hit--;if(enemy.alive){let dx=p.x-enemy.x,dy=p.y-enemy.y,d=Math.hypot(dx,dy);if(d<90&&d>0){enemy.x+=dx/d*.35;enemy.y+=dy/d*.35}if(hit(p,enemy)&&p.ifr<=0){p.hp=Math.max(0,p.hp-1);p.ifr=60;msg=p.hp?'Ouch. Keep moving!':'You fell. Refresh to try again.'}}}
function rect(o,col){x.fillStyle=col;x.fillRect(Math.round(o.x),Math.round(o.y),o.w,o.h)}
function draw(){x.fillStyle='#242817';x.fillRect(0,0,W,H);for(let yy=12;yy<168;yy+=16)for(let xx=12;xx<308;xx+=16){x.fillStyle=((xx+yy)/16)%2?'#30351d':'#2b301a';x.fillRect(xx,yy,16,16)}walls.forEach(w=>{rect(w,'#4b402b');x.fillStyle='#665638';x.fillRect(w.x,w.y,w.w,3)});rect(chest,chest.open?'#5d5635':'#79562b');x.fillStyle='#b58b45';x.fillRect(chest.x+5,chest.y+3,3,3);if(enemy.alive){rect(enemy,enemy.hit?'#d0b77b':'#57422c');x.fillStyle='#9db45a';x.fillRect(enemy.x+2,enemy.y+2,3,3);x.fillRect(enemy.x+7,enemy.y+2,3,3)}if(p.ifr%8<4){rect(p,'#24221b');x.fillStyle='#75894b';x.fillRect(p.x+2,p.y+2,6,7);x.fillStyle='#c4a96d';x.fillRect(p.x+3,p.y,4,3)}if(p.cool>10){x.strokeStyle='#d8c28a';x.beginPath();x.arc(p.x+5,p.y+6,15,0,Math.PI*1.3);x.stroke()}x.fillStyle='#16150fdd';x.fillRect(15,14,290,20);x.fillStyle='#d7cfb4';x.font='8px monospace';x.fillText(msg,22,27);for(let i=0;i<5;i++){x.fillStyle=i<p.hp?'#8d3e32':'#3b3028';x.fillRect(20+i*11,42,8,7)}if(won){x.fillStyle='#111b';x.fillRect(70,66,180,48);x.fillStyle='#d9d1ae';x.font='bold 13px monospace';x.fillText('DEORUM',132,85);x.font='8px monospace';x.fillText('FIRST PLAYABLE SLICE COMPLETE',91,101)}}
function loop(){update();draw();requestAnimationFrame(loop)}loop();
