const c=document.getElementById('game'),x=c.getContext('2d');x.imageSmoothingEnabled=false;
const W=c.width,H=c.height,keys={};let prevButtons=[];
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);
const rooms={
  evergreen:{name:'EVERGREEN EDGE',spawn:{x:32,y:86},walls:[{x:0,y:0,w:320,h:12},{x:0,y:168,w:320,h:12},{x:0,y:0,w:12,h:180},{x:45,y:38,w:54,h:12},{x:216,y:34,w:50,h:12},{x:69,y:122,w:45,h:12},{x:205,y:126,w:69,h:12},{x:142,y:68,w:36,h:18}],exit:{x:308,y:74,w:12,h:38,to:'greenwatch',spawn:{x:18,y:86}}},
  greenwatch:{name:'GREENWATCH TRAIL',spawn:{x:18,y:86},walls:[{x:0,y:0,w:320,h:12},{x:0,y:168,w:320,h:12},{x:308,y:0,w:12,h:180},{x:54,y:32,w:40,h:12},{x:118,y:122,w:52,h:12},{x:218,y:42,w:55,h:12},{x:205,y:130,w:60,h:12}],exit:{x:0,y:74,w:12,h:38,to:'evergreen',spawn:{x:292,y:86}}}
};
let roomId='evergreen',room=rooms[roomId];
const p={x:room.spawn.x,y:room.spawn.y,w:10,h:12,s:1.25,hp:5,dir:'down',ifr:0,step:0,combat:'idle',combatT:0,charge:0,hitDone:false};
const enemy={x:248,y:82,w:12,h:12,hp:3,alive:true,hit:0};
const npc={x:86,y:76,w:10,h:12,name:'Mosskeeper Elri',spoken:false};
const chest={x:275,y:144,w:13,h:10,open:false};
const inventory=[];let won=false,msg='Find Mosskeeper Elri.',transition=0;
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function blocked(nx,ny){const q={x:nx,y:ny,w:p.w,h:p.h};return room.walls.some(w=>hit(q,w))}
function gamepad(){const g=navigator.getGamepads?.()[0];if(!g)return {dx:0,dy:0,aDown:false,aPressed:false,aReleased:false,i:false};let dx=Math.abs(g.axes[0]||0)>.22?g.axes[0]:0,dy=Math.abs(g.axes[1]||0)>.22?g.axes[1]:0;const b=g.buttons,pressed=n=>!!b[n]?.pressed;const aDown=pressed(0),aPressed=aDown&&!prevButtons[0],aReleased=!aDown&&!!prevButtons[0],i=pressed(2)&&!prevButtons[2];prevButtons=b.map(v=>v.pressed);if(pressed(14))dx=-1;if(pressed(15))dx=1;if(pressed(12))dy=-1;if(pressed(13))dy=1;return{dx,dy,aDown,aPressed,aReleased,i}}
function save(){localStorage.setItem('deorum-third-chapter',JSON.stringify({roomId,p:{x:p.x,y:p.y,hp:p.hp},enemyAlive:enemy.alive,npcSpoken:npc.spoken,chestOpen:chest.open,inventory}));msg='Game saved.'}
function load(){try{const s=JSON.parse(localStorage.getItem('deorum-third-chapter'));if(!s)return;roomId=s.roomId||'evergreen';room=rooms[roomId];p.x=s.p?.x??room.spawn.x;p.y=s.p?.y??room.spawn.y;p.hp=s.p?.hp??5;enemy.alive=s.enemyAlive!==false;npc.spoken=!!s.npcSpoken;chest.open=!!s.chestOpen;inventory.splice(0,inventory.length,...(s.inventory||[]));won=inventory.includes('Green Relic');msg='Save loaded.'}catch{}}
function swordBox(range=15,pad=2){const a={x:p.x-pad,y:p.y-pad,w:p.w+pad*2,h:p.h+pad*2};if(p.dir==='left'){a.x-=range;a.w+=range}else if(p.dir==='right')a.w+=range;else if(p.dir==='up'){a.y-=range;a.h+=range}else a.h+=range;return a}
function damageEnemy(amount=1,box=swordBox()){if(roomId==='evergreen'&&enemy.alive&&hit(box,enemy)){enemy.hp-=amount;enemy.hit=8;if(enemy.hp<=0){enemy.alive=false;msg='The Thornling is defeated. Find the relic chest.'}return true}return false}
function beginSwing(){if(p.combat!=='idle'&&p.combat!=='charging')return;p.combat='swing';p.combatT=0;p.hitDone=false;p.charge=0}
function beginSpin(){p.combat='spin';p.combatT=0;p.hitDone=false;p.charge=0}
function updateCombat(attackDown,attackPressed,attackReleased){if(p.combat==='idle'&&attackPressed){p.combat='charging';p.combatT=0;p.charge=1}if(p.combat==='charging'){if(attackDown){p.charge=Math.min(48,p.charge+1);p.combatT++}if(attackReleased){if(p.charge>=32)beginSpin();else beginSwing()}}else if(p.combat==='swing'){p.combatT++;if(p.combatT>=3&&p.combatT<=8&&!p.hitDone){p.hitDone=damageEnemy(1,swordBox(16,1))}if(p.combatT>=12){p.combat='idle';p.combatT=0;p.hitDone=false}}else if(p.combat==='spin'){p.combatT++;if(p.combatT>=2&&p.combatT<=14&&!p.hitDone){const q={x:p.x-13,y:p.y-12,w:p.w+26,h:p.h+24};p.hitDone=damageEnemy(2,q)}if(p.combatT>=20){p.combat='idle';p.combatT=0;p.hitDone=false}}}
function interact(){const q={x:p.x-10,y:p.y-10,w:p.w+20,h:p.h+20};if(roomId==='evergreen'&&hit(q,npc)){npc.spoken=true;msg='Elri: “The old Green Relic lies beyond the Thornling.”';save();return}if(roomId==='evergreen'&&hit(q,chest)&&!chest.open){if(enemy.alive){msg='A thorny presence guards the relic.';return}chest.open=true;if(!inventory.includes('Green Relic'))inventory.push('Green Relic');won=true;msg='GREEN RELIC recovered. The eastern trail is open.';save();return}if(roomId==='greenwatch'){msg='The road bends east toward Greenwatch Harbor.'}}
function changeRoom(to,spawn){roomId=to;room=rooms[roomId];p.x=spawn.x;p.y=spawn.y;transition=18;msg=roomId==='greenwatch'?'You enter Greenwatch Trail.':'You return to Evergreen Edge.';save()}
function update(){const g=gamepad();const kbDown=!!keys.Space,kbPressed=kbDown&&!update.prevSpace,kbReleased=!kbDown&&update.prevSpace;update.prevSpace=kbDown;const attackDown=kbDown||g.aDown,attackPressed=kbPressed||g.aPressed,attackReleased=kbReleased||g.aReleased;updateCombat(attackDown,attackPressed,attackReleased);let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+g.dx,dy=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+g.dy;const moveScale=p.combat==='charging'?.72:p.combat==='spin'?.45:1;if(dx||dy){p.step=(p.step+1)%40;const m=Math.hypot(dx,dy)||1;dx/=m;dy/=m;if(p.combat!=='spin'){if(Math.abs(dx)>Math.abs(dy))p.dir=dx<0?'left':'right';else p.dir=dy<0?'up':'down'}let nx=p.x+dx*p.s*moveScale,ny=p.y;if(!blocked(nx,ny))p.x=nx;nx=p.x;ny=p.y+dy*p.s*moveScale;if(!blocked(nx,ny))p.y=ny}if((keys.KeyE||g.i)){interact();keys.KeyE=false}if(keys.KeyK){save();keys.KeyK=false}if(keys.KeyL){load();keys.KeyL=false}if(p.ifr>0)p.ifr--;if(enemy.hit>0)enemy.hit--;if(roomId==='evergreen'&&enemy.alive){let dx=p.x-enemy.x,dy=p.y-enemy.y,d=Math.hypot(dx,dy);if(d<88&&d>0){enemy.x+=dx/d*.32;enemy.y+=dy/d*.32}if(hit(p,enemy)&&p.ifr<=0){p.hp=Math.max(0,p.hp-1);p.ifr=60;msg=p.hp?'The Thornling clips you!':'You fell. Press L to load your save.'}}const q={x:p.x,y:p.y,w:p.w,h:p.h};if(hit(q,room.exit)){if(roomId==='evergreen'&&!won){msg='The eastern trail feels unfinished. Find the relic first.';p.x=294}else changeRoom(room.exit.to,room.exit.spawn)}if(transition>0)transition--}
function rect(o,col){x.fillStyle=col;x.fillRect(Math.round(o.x),Math.round(o.y),o.w,o.h)}
function tree(tx,ty){x.fillStyle='#1b1b12';x.fillRect(tx+5,ty+10,4,10);x.fillStyle='#384021';x.fillRect(tx+1,ty+3,12,10);x.fillStyle='#4f5b2b';x.fillRect(tx+3,ty,8,7)}
function stone(sx,sy){x.fillStyle='#40382a';x.fillRect(sx,sy,9,6);x.fillStyle='#5b4d36';x.fillRect(sx+1,sy,7,2)}
function drawGround(){x.fillStyle=roomId==='evergreen'?'#202514':'#1e2418';x.fillRect(0,0,W,H);for(let yy=12;yy<168;yy+=8)for(let xx=12;xx<308;xx+=8){x.fillStyle=((xx+yy)/8)%3===0?'#2a3119':'#252b17';x.fillRect(xx,yy,8,8)}x.fillStyle='#4a4028';x.fillRect(12,81,296,21);x.fillStyle='#655333';for(let xx=16;xx<304;xx+=16)x.fillRect(xx,89,10,3);if(roomId==='evergreen'){x.fillStyle='#26321d';x.fillRect(122,12,78,45);x.fillStyle='#314328';x.fillRect(126,16,70,37)}else{x.fillStyle='#26311f';x.fillRect(150,12,22,64);x.fillRect(150,104,22,64)}}
function drawLandmarks(){if(roomId==='evergreen'){[[20,22],[34,18],[278,20],[292,30],[18,134],[32,142],[282,132],[294,144]].forEach(([a,b])=>tree(a,b));[[118,28],[187,27],[132,141],[184,147]].forEach(([a,b])=>stone(a,b));x.fillStyle='#16150f';x.fillRect(141,68,38,18);x.fillStyle='#5c4a2c';x.fillRect(145,72,30,10);x.fillStyle='#7a633a';x.fillRect(153,74,14,2);x.fillStyle='#71884b';x.fillRect(160,65,3,5)}else{[[22,20],[42,30],[270,22],[290,18],[24,138],[52,142],[274,134],[292,146],[112,24],[190,136]].forEach(([a,b])=>tree(a,b));[[98,66],[220,106],[186,48]].forEach(([a,b])=>stone(a,b));x.fillStyle='#6a5735';x.fillRect(236,70,6,25);x.fillRect(228,76,22,4);x.fillStyle='#8a7448';x.fillRect(232,73,14,3)}}
function drawPlayer(){if(p.ifr%8>=4)return;const bob=p.step<20?0:1;rect({x:p.x,y:p.y+bob,w:p.w,h:p.h},'#1a1814');x.fillStyle='#708449';x.fillRect(p.x+2,p.y+2+bob,6,7);x.fillStyle='#c1a56b';x.fillRect(p.x+3,p.y+bob,4,3);x.fillStyle='#40311f';x.fillRect(p.x+1,p.y+9+bob,3,3);x.fillRect(p.x+6,p.y+9+bob,3,3)}
function drawNPC(){rect(npc,'#211f17');x.fillStyle='#66763d';x.fillRect(npc.x+2,npc.y+3,6,7);x.fillStyle='#d0b47b';x.fillRect(npc.x+3,npc.y,4,4);x.fillStyle='#8d7a4a';x.fillRect(npc.x+8,npc.y+2,2,10);x.fillStyle='#82985b';x.fillRect(npc.x+7,npc.y,4,3)}
function drawEnemy(){if(!enemy.alive)return;rect(enemy,enemy.hit?'#c5ad6c':'#493b28');x.fillStyle='#6b7f3e';x.fillRect(enemy.x+1,enemy.y+1,10,8);x.fillStyle='#1a1710';x.fillRect(enemy.x+3,enemy.y+3,2,2);x.fillRect(enemy.x+7,enemy.y+3,2,2);x.fillStyle='#7b663d';x.fillRect(enemy.x+2,enemy.y+9,2,4);x.fillRect(enemy.x+8,enemy.y+9,2,4)}
function drawSword(){const cx=p.x+5,cy=p.y+6;if(p.combat==='charging'){const r=9+Math.min(7,p.charge/6);x.strokeStyle=p.charge>=32?'#efe4a6':'#b9a66a';x.beginPath();x.arc(cx,cy,r,0,Math.PI*2*(p.charge/48));x.stroke();return}if(p.combat==='spin'){x.strokeStyle='#efe4a6';x.lineWidth=2;x.beginPath();x.arc(cx,cy,15,Math.PI*(p.combatT/10),Math.PI*(p.combatT/10)+Math.PI*1.4);x.stroke();x.lineWidth=1;return}if(p.combat==='swing'){const progress=Math.min(1,p.combatT/10),base={right:0,left:Math.PI,up:-Math.PI/2,down:Math.PI/2}[p.dir],ang=base-.95+progress*1.9;x.strokeStyle='#e7d8a0';x.lineWidth=2;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(ang)*17,cy+Math.sin(ang)*17);x.stroke();x.lineWidth=1}}
function draw(){drawGround();drawLandmarks();room.walls.forEach(w=>{rect(w,'#443923');x.fillStyle='#625235';x.fillRect(w.x,w.y,w.w,3)});if(roomId==='evergreen'){drawNPC();rect(chest,chest.open?'#4f5833':'#72512b');x.fillStyle='#b58b45';x.fillRect(chest.x+5,chest.y+3,3,3);drawEnemy()}drawPlayer();drawSword();x.fillStyle='#11120ddd';x.fillRect(13,12,294,22);x.fillStyle='#d7cfb4';x.font='8px monospace';x.fillText(msg,19,26);for(let i=0;i<5;i++){x.fillStyle=i<p.hp?'#8d3e32':'#3b3028';x.fillRect(18+i*11,40,8,7)}if(p.combat==='charging'){x.fillStyle='#d7cfb4';x.fillText(p.charge>=32?'SPIN READY':'CHARGING...',232,44)}x.fillStyle='#d7cfb4';x.font='7px monospace';x.fillText(room.name,232,164);x.fillText('ITEMS: '+(inventory.length?inventory.join(', '):'—'),18,164);if(transition>0){x.fillStyle='#0008';x.fillRect(0,0,W,H)}if(won&&roomId==='greenwatch'){x.fillStyle='#111b';x.fillRect(62,61,196,55);x.fillStyle='#d9d1ae';x.font='bold 13px monospace';x.fillText('DEORUM',132,82);x.font='8px monospace';x.fillText('THE THIRD CHAPTER',112,96);x.fillText('THE ROAD CONTINUES...',103,108)}}
function loop(){update();draw();requestAnimationFrame(loop)}load();loop();
